---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signer
  namespace: {{ template "karb.namespace" $ }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karb-admission-certificate
  namespace: {{ template "karb.namespace" $ }}
spec:
  secretName: karb-admission-certificate-secret
  dnsNames:
    - karb-admission-svc.{{ template "karb.namespace" $ }}.svc
  issuerRef:
    name: self-signer
