---
kind: Service
apiVersion: v1
metadata:
  name: karb-admission-svc
  namespace: {{ template "karb.namespace" $ }}
  labels:
    {{- include "karb.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8443
  {{- if .Values.operator.metrics.enabled }}
    - name: metric
      port: {{ .Values.operator.metrics.port }}
      targetPort: 9090
  {{- end }}
  selector:
    {{- include "karb.selectorLabels" . | indent 4 }}
