name: karb
version: 1.0.0
apiVersion: v2
appVersion: 0.3.0
# home: https://...
description: k8s App-controlled Restore & Backup. Another kind of doing backup.
keywords:
  - kubernetes
  - backup
maintainers:
  - name: xeor
    email: lars.solberg+karb@gmail.com
kubeVersion: ">=1.9.0-0"
